export const SITE = 'https://bhupimahey.in';
export const EMAIL = 'bhupimahey@gmail.com';
export const services = [
 { slug:'web-application-development', title:'Web Application Development', short:'Custom portals, dashboards and business systems.', solves:'Manual, spreadsheet-based or outdated processes that need a reliable web system.', who:'Businesses and agencies that need custom portals, dashboards or internal tools.', deliver:['Requirements and architecture','Responsive web application','Admin panel and user roles','Testing and deployment'], tech:'PHP, CodeIgniter, Symfony, JavaScript, React, MySQL', benefits:['Software that fits your workflow','Maintainable, structured code','Room to grow with the business'] },
 { slug:'saas-development', title:'SaaS Development', short:'From MVP to multi-user product.', solves:'Turning a product idea into a working multi-user platform.', who:'Startups and founders validating or scaling a product.', deliver:['MVP scoping','Accounts, roles and subscriptions','Payment gateway integration','Dashboards, reporting and iterative releases'], tech:'PHP, Symfony, CodeIgniter, React, MySQL, REST APIs', benefits:['A usable MVP sooner','Architecture that can scale','Direct access to the engineer building it'] },
 { slug:'ecommerce-payments', title:'E-commerce & Payment Integration', short:'Online stores and reliable payment flows.', solves:'Online stores that need custom features or dependable payment handling.', who:'Retailers, and agencies building stores for clients.', deliver:['OpenCart or custom store build','Payment gateway integration','Catalogue, orders and customer accounts','Customisation, fixes and upgrades'], tech:'OpenCart, WordPress, PHP, MySQL, payment gateway APIs', benefits:['Checkout that works as expected','Store features tailored to your business','Fewer manual order and stock tasks'] },
 { slug:'api-integrations', title:'API & System Integrations', short:'Connect the tools your business already uses.', solves:'Systems and services that do not talk to each other.', who:'Businesses connecting platforms, third-party services and internal tools.', deliver:['REST API design and build','Third-party API integration','Data synchronisation and automation','API documentation'], tech:'PHP, REST APIs, JavaScript, MySQL', benefits:['Less duplicate data entry','One source of truth across systems','Integrations that are documented and maintainable'] },
 { slug:'ai-automation', title:'AI & Automation', short:'AI applied to defined business tasks.', solves:'Repetitive, document-heavy or manual workflows.', who:'Businesses and product teams adding AI features to existing software.', deliver:['Use-case assessment','API-based LLM integration','Document processing and data extraction','Workflow automation'], tech:'PHP, JavaScript, REST APIs to third-party AI services', benefits:['Time saved on repetitive work','AI added where it has a clear purpose','Built into the software you already run'] },
 { slug:'maintenance-dedicated-development', title:'Maintenance & Dedicated Development', short:'Ongoing capacity and legacy modernization.', solves:'Ageing, unmaintained applications, and teams short on developers.', who:'Agencies and businesses that need ongoing development capacity.', deliver:['Code review and modernization plan','Upgrades and refactoring','Bug fixing and updates','Monthly dedicated development'], tech:'PHP, CodeIgniter, Symfony, WordPress, OpenCart, MySQL', benefits:['Stable, supported software','Predictable ongoing capacity','A single long-term technical contact'] },
];
export const work = ['Indian Super Store','Trade M Global','Pizza Buddy','Prestige Accommodation','Exodus Long Boards','Catholic High Alumni','Vira Clothings','Acakid','Pitstop','Perth City Cranes','TSM Nany'];
export const flow = ['Agency receives the client requirement','Requirement shared with me','Development','QA','Delivery','Agency delivers to the client'];
export const techGroups = [['Backend','PHP, CodeIgniter, Symfony, REST APIs'],['Frontend','JavaScript, React, jQuery, AJAX, HTML, CSS'],['CMS & Commerce','WordPress, OpenCart'],['Database','MySQL']];
export const steps = [['Discovery','Goals, users and constraints, agreed before any code.'],['Architecture','Data model, integrations and a stack that can scale.'],['UI/UX','Clear flows and interfaces, or your designer’s files implemented faithfully.'],['Development','Iterative builds with regular, visible progress.'],['QA & Launch','Testing, deployment and handover.'],['Support & Growth','Maintenance and new features as the product grows.']];
export const faq = [['Can you work under an NDA?','Yes. NDA-friendly collaboration is standard for agency and white-label work.'],['Which time zone do you work in?','India Standard Time, with overlap hours agreed per project for clients in the USA, UK, Canada, Australia and Europe.'],['How do engagements work?','Project-based or ongoing monthly development, depending on scope. Send a brief and I will propose the best fit.']];

export const GITHUB = 'https://github.com/bhupimahey';
export const LINKEDIN = ''; // add your LinkedIn profile URL to show its icon in the footer
export const WHATSAPP = 'https://wa.me/919041959311';
export const nav = [['Home', '/'], ['Services', '/services/'], ['Solutions', '/solutions/'], ['Work', '/work/'], ['About', '/about/'], ['Insights', '/insights/'], ['Contact', '/contact/']];
export const stats = [['calendar', '12+', 'Years Experience'], ['layers', '200+', 'Completed Projects'], ['users', '200+', 'Clients Worldwide'], ['globe', 'Global Delivery', 'USA, UK, Canada, Australia & More']];
export const hs = [['monitor', 'Web Application Development', 'Scalable web applications and SaaS platforms.', '/services/web-application-development/'], ['cpu', 'AI & Automation', 'Integrate AI to automate and grow your business.', '/services/ai-automation/'], ['phone', 'Mobile App Development', 'iOS & Android app development.', '/services/'], ['layers', 'Custom Business Software', 'Tailored software for your unique needs.', '/services/web-application-development/'], ['link', 'API & Integrations', 'Connect your systems and third-party APIs.', '/services/api-integrations/'], ['users', 'White-Label Development', 'Your clients. Your brand. Your development partner.', '/white-label/']];
export const projects = [['Web Application', 'Business Management Platform', 'Custom web application with dashboard, reports and multi-user system.', 't0'], ['SaaS Development', 'Accounting & Finance Software', 'Complete accounting solution with reports, GST and integrations.', 't1'], ['Mobile App', 'iOS & Android Application', 'Feature-rich mobile app with modern UI/UX and seamless app performance.', 't2']];
export const benefits = [['message', 'Direct Communication', 'Work directly with an experienced developer.'], ['refresh', 'Flexible Engagement', 'Hourly, fixed or dedicated team model.'], ['shield', 'Long-Term Partnership', 'Ongoing support and maintenance.'], ['layers', 'Modern Technologies', 'Always up to date with latest tech.'], ['target', 'Business-Focused Approach', 'Understand your business goals.'], ['globe', 'International Client Ready', 'Timezone-friendly collaboration.']];
export const audience = [['building', 'For Businesses', 'Streamline operations and modernize your systems.', 'businesses'], ['rocket', 'For Startups', 'Build and scale your product with the right technology.', 'startups'], ['users', 'For Agencies', 'White-label development for your client projects.', 'agencies']];
export const steps2 = [['search', 'Discovery', 'Understand your goals and requirements.'], ['layers', 'Planning & Architecture', 'Define the right solution and technology stack.'], ['pencil', 'UI/UX Design', 'Create modern and user-friendly designs.'], ['code', 'Development', 'Agile development with regular updates.'], ['check', 'Testing & Launch', 'Quality assurance and smooth launch.'], ['life', 'Support & Growth', 'Ongoing support and future enhancements.']];
// SAMPLE testimonials (layout placeholders). Replace with verified client feedback, then set SAMPLE_TESTIMONIALS = false.
export const SAMPLE_TESTIMONIALS = true;
export const testi = [['Great developer to work with. Very professional, clear communication and high-quality work. Highly recommended for long-term projects.', 'John D.', 'USA'], ['Delivered our project on time with excellent quality. Very reliable and understands business requirements well.', 'Sarah M.', 'UK'], ['A trusted development partner for our agency. Always delivers great results and is easy to work with.', 'Michael T.', 'Australia']];
